// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FTProtocol_v3.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ft.Protocol {

  /// <summary>Holder for reflection information generated from FTProtocol_v3.proto</summary>
  public static partial class FTProtocolV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for FTProtocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FTProtocolV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNGVFByb3RvY29sX3YzLnByb3RvEgtmdC5wcm90b2NvbCIyCgZPZmljaXUS",
            "CgoCaWQYASABKAkSDAoEbnVtZRgCIAEoCRIOCgZwYXJvbGEYAyABKAkiUwoF",
            "Q3Vyc2ESCgoCaWQYASABKAkSEgoKZGVzdGluYXRpZRgCIAEoCRIPCgdwbGVj",
            "YXJlGAMgASgJEhkKEWxvY3VyaURpc3BvbmliaWxlGAQgASgJIk4KCVJlemVy",
            "dmFyZRIKCgJpZBgBIAEoCRISCgpudW1lQ2xpZW50GAIgASgJEhAKCG5yTG9j",
            "dXJpGAMgASgJEg8KB2lkQ3Vyc2EYBCABKAkiMQoMUmV6ZXJ2YXJlRFRPEhIK",
            "Cm51bWVDbGllbnQYASABKAkSDQoFbnJMb2MYAiABKAki7AIKB1JlcXVlc3QS",
            "JwoEdHlwZRgBIAEoDjIZLmZ0LnByb3RvY29sLlJlcXVlc3QuVHlwZRIlCgZv",
            "ZmljaXUYAiABKAsyEy5mdC5wcm90b2NvbC5PZmljaXVIABIjCgVjdXJzYRgD",
            "IAEoCzISLmZ0LnByb3RvY29sLkN1cnNhSAASKwoJcmV6ZXJ2YXJlGAQgASgL",
            "MhYuZnQucHJvdG9jb2wuUmV6ZXJ2YXJlSAASMQoMcmV6ZXJ2YXJlRFRPGAUg",
            "ASgLMhkuZnQucHJvdG9jb2wuUmV6ZXJ2YXJlRFRPSAAigAEKBFR5cGUSCwoH",
            "VW5rbm93bhAAEgkKBUxPR0lOEAESCgoGTE9HT1VUEAISFgoSR0VUX0ZJTFRF",
            "UkVEX0NVUlNFEAMSEgoOU0FWRV9SRVpFUlZBUkUQBBIRCg1HRVRfQUxMX0NV",
            "UlNFEAUSFQoRR0VUX1JFWkVSVkFSRV9EVE8QBkIJCgdwYXlsb2FkIvoDCghS",
            "ZXNwb25zZRIoCgR0eXBlGAEgASgOMhouZnQucHJvdG9jb2wuUmVzcG9uc2Uu",
            "VHlwZRINCgVlcnJvchgCIAEoCRIjCgZvZmljaXUYAyABKAsyEy5mdC5wcm90",
            "b2NvbC5PZmljaXUSIQoFY3Vyc2UYBCADKAsyEi5mdC5wcm90b2NvbC5DdXJz",
            "YRIhCgVjdXJzYRgFIAEoCzISLmZ0LnByb3RvY29sLkN1cnNhEikKCXJlemVy",
            "dmFyZRgGIAEoCzIWLmZ0LnByb3RvY29sLlJlemVydmFyZRIpCglyZXplcnZh",
            "cmkYByADKAsyFi5mdC5wcm90b2NvbC5SZXplcnZhcmUSLwoMcmV6ZXJ2YXJl",
            "RFRPGAggASgLMhkuZnQucHJvdG9jb2wuUmV6ZXJ2YXJlRFRPEi8KDHJlemVy",
            "dmFyaURUTxgJIAMoCzIZLmZ0LnByb3RvY29sLlJlemVydmFyZURUTyKRAQoE",
            "VHlwZRILCgdVbmtub3duEAASBgoCT2sQARIJCgVFcnJvchACEhYKEkdFVF9G",
            "SUxURVJFRF9DVVJTRRADEhIKDlNBVkVfUkVaRVJWQVJFEAQSEwoPU0FWRURf",
            "UkVaRVJWQVJFEAUSEQoNR0VUX0FMTF9DVVJTRRAGEhUKEUdFVF9SRVpFUlZB",
            "UkVfRFRPEAdCIAoRcHJvdG9idWZmcHJvdG9jb2xCC0ZUUHJvdG9idWZzYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ft.Protocol.Oficiu), global::Ft.Protocol.Oficiu.Parser, new[]{ "Id", "Nume", "Parola" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ft.Protocol.Cursa), global::Ft.Protocol.Cursa.Parser, new[]{ "Id", "Destinatie", "Plecare", "LocuriDisponibile" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ft.Protocol.Rezervare), global::Ft.Protocol.Rezervare.Parser, new[]{ "Id", "NumeClient", "NrLocuri", "IdCursa" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ft.Protocol.RezervareDTO), global::Ft.Protocol.RezervareDTO.Parser, new[]{ "NumeClient", "NrLoc" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ft.Protocol.Request), global::Ft.Protocol.Request.Parser, new[]{ "Type", "Oficiu", "Cursa", "Rezervare", "RezervareDTO" }, new[]{ "Payload" }, new[]{ typeof(global::Ft.Protocol.Request.Types.Type) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ft.Protocol.Response), global::Ft.Protocol.Response.Parser, new[]{ "Type", "Error", "Oficiu", "Curse", "Cursa", "Rezervare", "Rezervari", "RezervareDTO", "RezervariDTO" }, null, new[]{ typeof(global::Ft.Protocol.Response.Types.Type) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Oficiu : pb::IMessage<Oficiu> {
    private static readonly pb::MessageParser<Oficiu> _parser = new pb::MessageParser<Oficiu>(() => new Oficiu());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Oficiu> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ft.Protocol.FTProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Oficiu() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Oficiu(Oficiu other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      parola_ = other.parola_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Oficiu Clone() {
      return new Oficiu(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parola" field.</summary>
    public const int ParolaFieldNumber = 3;
    private string parola_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parola {
      get { return parola_; }
      set {
        parola_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Oficiu);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Oficiu other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (Parola != other.Parola) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Parola.Length != 0) hash ^= Parola.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Parola);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Parola.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parola);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Oficiu other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Parola.Length != 0) {
        Parola = other.Parola;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Cursa : pb::IMessage<Cursa> {
    private static readonly pb::MessageParser<Cursa> _parser = new pb::MessageParser<Cursa>(() => new Cursa());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Cursa> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ft.Protocol.FTProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cursa() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cursa(Cursa other) : this() {
      id_ = other.id_;
      destinatie_ = other.destinatie_;
      plecare_ = other.plecare_;
      locuriDisponibile_ = other.locuriDisponibile_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cursa Clone() {
      return new Cursa(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "destinatie" field.</summary>
    public const int DestinatieFieldNumber = 2;
    private string destinatie_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Destinatie {
      get { return destinatie_; }
      set {
        destinatie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plecare" field.</summary>
    public const int PlecareFieldNumber = 3;
    private string plecare_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Plecare {
      get { return plecare_; }
      set {
        plecare_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locuriDisponibile" field.</summary>
    public const int LocuriDisponibileFieldNumber = 4;
    private string locuriDisponibile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LocuriDisponibile {
      get { return locuriDisponibile_; }
      set {
        locuriDisponibile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Cursa);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Cursa other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Destinatie != other.Destinatie) return false;
      if (Plecare != other.Plecare) return false;
      if (LocuriDisponibile != other.LocuriDisponibile) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Destinatie.Length != 0) hash ^= Destinatie.GetHashCode();
      if (Plecare.Length != 0) hash ^= Plecare.GetHashCode();
      if (LocuriDisponibile.Length != 0) hash ^= LocuriDisponibile.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Destinatie.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Destinatie);
      }
      if (Plecare.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Plecare);
      }
      if (LocuriDisponibile.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LocuriDisponibile);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Destinatie.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destinatie);
      }
      if (Plecare.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Plecare);
      }
      if (LocuriDisponibile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LocuriDisponibile);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Cursa other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Destinatie.Length != 0) {
        Destinatie = other.Destinatie;
      }
      if (other.Plecare.Length != 0) {
        Plecare = other.Plecare;
      }
      if (other.LocuriDisponibile.Length != 0) {
        LocuriDisponibile = other.LocuriDisponibile;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Destinatie = input.ReadString();
            break;
          }
          case 26: {
            Plecare = input.ReadString();
            break;
          }
          case 34: {
            LocuriDisponibile = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Rezervare : pb::IMessage<Rezervare> {
    private static readonly pb::MessageParser<Rezervare> _parser = new pb::MessageParser<Rezervare>(() => new Rezervare());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Rezervare> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ft.Protocol.FTProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rezervare() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rezervare(Rezervare other) : this() {
      id_ = other.id_;
      numeClient_ = other.numeClient_;
      nrLocuri_ = other.nrLocuri_;
      idCursa_ = other.idCursa_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rezervare Clone() {
      return new Rezervare(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numeClient" field.</summary>
    public const int NumeClientFieldNumber = 2;
    private string numeClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumeClient {
      get { return numeClient_; }
      set {
        numeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuri" field.</summary>
    public const int NrLocuriFieldNumber = 3;
    private string nrLocuri_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "idCursa" field.</summary>
    public const int IdCursaFieldNumber = 4;
    private string idCursa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdCursa {
      get { return idCursa_; }
      set {
        idCursa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Rezervare);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Rezervare other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NumeClient != other.NumeClient) return false;
      if (NrLocuri != other.NrLocuri) return false;
      if (IdCursa != other.IdCursa) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (NumeClient.Length != 0) hash ^= NumeClient.GetHashCode();
      if (NrLocuri.Length != 0) hash ^= NrLocuri.GetHashCode();
      if (IdCursa.Length != 0) hash ^= IdCursa.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeClient);
      }
      if (NrLocuri.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NrLocuri);
      }
      if (IdCursa.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdCursa);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (NumeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeClient);
      }
      if (NrLocuri.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NrLocuri);
      }
      if (IdCursa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCursa);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Rezervare other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.NumeClient.Length != 0) {
        NumeClient = other.NumeClient;
      }
      if (other.NrLocuri.Length != 0) {
        NrLocuri = other.NrLocuri;
      }
      if (other.IdCursa.Length != 0) {
        IdCursa = other.IdCursa;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            NumeClient = input.ReadString();
            break;
          }
          case 26: {
            NrLocuri = input.ReadString();
            break;
          }
          case 34: {
            IdCursa = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RezervareDTO : pb::IMessage<RezervareDTO> {
    private static readonly pb::MessageParser<RezervareDTO> _parser = new pb::MessageParser<RezervareDTO>(() => new RezervareDTO());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RezervareDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ft.Protocol.FTProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RezervareDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RezervareDTO(RezervareDTO other) : this() {
      numeClient_ = other.numeClient_;
      nrLoc_ = other.nrLoc_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RezervareDTO Clone() {
      return new RezervareDTO(this);
    }

    /// <summary>Field number for the "numeClient" field.</summary>
    public const int NumeClientFieldNumber = 1;
    private string numeClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumeClient {
      get { return numeClient_; }
      set {
        numeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLoc" field.</summary>
    public const int NrLocFieldNumber = 2;
    private string nrLoc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NrLoc {
      get { return nrLoc_; }
      set {
        nrLoc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RezervareDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RezervareDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumeClient != other.NumeClient) return false;
      if (NrLoc != other.NrLoc) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NumeClient.Length != 0) hash ^= NumeClient.GetHashCode();
      if (NrLoc.Length != 0) hash ^= NrLoc.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NumeClient.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumeClient);
      }
      if (NrLoc.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NrLoc);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NumeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeClient);
      }
      if (NrLoc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NrLoc);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RezervareDTO other) {
      if (other == null) {
        return;
      }
      if (other.NumeClient.Length != 0) {
        NumeClient = other.NumeClient;
      }
      if (other.NrLoc.Length != 0) {
        NrLoc = other.NrLoc;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            NumeClient = input.ReadString();
            break;
          }
          case 18: {
            NrLoc = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Request : pb::IMessage<Request> {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ft.Protocol.FTProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Oficiu:
          Oficiu = other.Oficiu.Clone();
          break;
        case PayloadOneofCase.Cursa:
          Cursa = other.Cursa.Clone();
          break;
        case PayloadOneofCase.Rezervare:
          Rezervare = other.Rezervare.Clone();
          break;
        case PayloadOneofCase.RezervareDTO:
          RezervareDTO = other.RezervareDTO.Clone();
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ft.Protocol.Request.Types.Type type_ = 0;
    /// <summary>
    ///  Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.Request.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "oficiu" field.</summary>
    public const int OficiuFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.Oficiu Oficiu {
      get { return payloadCase_ == PayloadOneofCase.Oficiu ? (global::Ft.Protocol.Oficiu) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Oficiu;
      }
    }

    /// <summary>Field number for the "cursa" field.</summary>
    public const int CursaFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.Cursa Cursa {
      get { return payloadCase_ == PayloadOneofCase.Cursa ? (global::Ft.Protocol.Cursa) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Cursa;
      }
    }

    /// <summary>Field number for the "rezervare" field.</summary>
    public const int RezervareFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.Rezervare Rezervare {
      get { return payloadCase_ == PayloadOneofCase.Rezervare ? (global::Ft.Protocol.Rezervare) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Rezervare;
      }
    }

    /// <summary>Field number for the "rezervareDTO" field.</summary>
    public const int RezervareDTOFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.RezervareDTO RezervareDTO {
      get { return payloadCase_ == PayloadOneofCase.RezervareDTO ? (global::Ft.Protocol.RezervareDTO) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RezervareDTO;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Oficiu = 2,
      Cursa = 3,
      Rezervare = 4,
      RezervareDTO = 5,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Oficiu, other.Oficiu)) return false;
      if (!object.Equals(Cursa, other.Cursa)) return false;
      if (!object.Equals(Rezervare, other.Rezervare)) return false;
      if (!object.Equals(RezervareDTO, other.RezervareDTO)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Oficiu) hash ^= Oficiu.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Cursa) hash ^= Cursa.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Rezervare) hash ^= Rezervare.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RezervareDTO) hash ^= RezervareDTO.GetHashCode();
      hash ^= (int) payloadCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Oficiu) {
        output.WriteRawTag(18);
        output.WriteMessage(Oficiu);
      }
      if (payloadCase_ == PayloadOneofCase.Cursa) {
        output.WriteRawTag(26);
        output.WriteMessage(Cursa);
      }
      if (payloadCase_ == PayloadOneofCase.Rezervare) {
        output.WriteRawTag(34);
        output.WriteMessage(Rezervare);
      }
      if (payloadCase_ == PayloadOneofCase.RezervareDTO) {
        output.WriteRawTag(42);
        output.WriteMessage(RezervareDTO);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Oficiu) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Oficiu);
      }
      if (payloadCase_ == PayloadOneofCase.Cursa) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cursa);
      }
      if (payloadCase_ == PayloadOneofCase.Rezervare) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rezervare);
      }
      if (payloadCase_ == PayloadOneofCase.RezervareDTO) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RezervareDTO);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Oficiu:
          Oficiu = other.Oficiu;
          break;
        case PayloadOneofCase.Cursa:
          Cursa = other.Cursa;
          break;
        case PayloadOneofCase.Rezervare:
          Rezervare = other.Rezervare;
          break;
        case PayloadOneofCase.RezervareDTO:
          RezervareDTO = other.RezervareDTO;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::Ft.Protocol.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ft.Protocol.Oficiu subBuilder = new global::Ft.Protocol.Oficiu();
            if (payloadCase_ == PayloadOneofCase.Oficiu) {
              subBuilder.MergeFrom(Oficiu);
            }
            input.ReadMessage(subBuilder);
            Oficiu = subBuilder;
            break;
          }
          case 26: {
            global::Ft.Protocol.Cursa subBuilder = new global::Ft.Protocol.Cursa();
            if (payloadCase_ == PayloadOneofCase.Cursa) {
              subBuilder.MergeFrom(Cursa);
            }
            input.ReadMessage(subBuilder);
            Cursa = subBuilder;
            break;
          }
          case 34: {
            global::Ft.Protocol.Rezervare subBuilder = new global::Ft.Protocol.Rezervare();
            if (payloadCase_ == PayloadOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
          case 42: {
            global::Ft.Protocol.RezervareDTO subBuilder = new global::Ft.Protocol.RezervareDTO();
            if (payloadCase_ == PayloadOneofCase.RezervareDTO) {
              subBuilder.MergeFrom(RezervareDTO);
            }
            input.ReadMessage(subBuilder);
            RezervareDTO = subBuilder;
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("LOGIN")] Login = 1,
        [pbr::OriginalName("LOGOUT")] Logout = 2,
        [pbr::OriginalName("GET_FILTERED_CURSE")] GetFilteredCurse = 3,
        [pbr::OriginalName("SAVE_REZERVARE")] SaveRezervare = 4,
        [pbr::OriginalName("GET_ALL_CURSE")] GetAllCurse = 5,
        [pbr::OriginalName("GET_REZERVARE_DTO")] GetRezervareDto = 6,
      }

    }
    #endregion

  }

  public sealed partial class Response : pb::IMessage<Response> {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ft.Protocol.FTProtocolV3Reflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response(Response other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      Oficiu = other.oficiu_ != null ? other.Oficiu.Clone() : null;
      curse_ = other.curse_.Clone();
      Cursa = other.cursa_ != null ? other.Cursa.Clone() : null;
      Rezervare = other.rezervare_ != null ? other.Rezervare.Clone() : null;
      rezervari_ = other.rezervari_.Clone();
      RezervareDTO = other.rezervareDTO_ != null ? other.RezervareDTO.Clone() : null;
      rezervariDTO_ = other.rezervariDTO_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ft.Protocol.Response.Types.Type type_ = 0;
    /// <summary>
    ///  Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.Response.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    /// <summary>
    ///  One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oficiu" field.</summary>
    public const int OficiuFieldNumber = 3;
    private global::Ft.Protocol.Oficiu oficiu_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.Oficiu Oficiu {
      get { return oficiu_; }
      set {
        oficiu_ = value;
      }
    }

    /// <summary>Field number for the "curse" field.</summary>
    public const int CurseFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Ft.Protocol.Cursa> _repeated_curse_codec
        = pb::FieldCodec.ForMessage(34, global::Ft.Protocol.Cursa.Parser);
    private readonly pbc::RepeatedField<global::Ft.Protocol.Cursa> curse_ = new pbc::RepeatedField<global::Ft.Protocol.Cursa>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Ft.Protocol.Cursa> Curse {
      get { return curse_; }
    }

    /// <summary>Field number for the "cursa" field.</summary>
    public const int CursaFieldNumber = 5;
    private global::Ft.Protocol.Cursa cursa_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.Cursa Cursa {
      get { return cursa_; }
      set {
        cursa_ = value;
      }
    }

    /// <summary>Field number for the "rezervare" field.</summary>
    public const int RezervareFieldNumber = 6;
    private global::Ft.Protocol.Rezervare rezervare_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.Rezervare Rezervare {
      get { return rezervare_; }
      set {
        rezervare_ = value;
      }
    }

    /// <summary>Field number for the "rezervari" field.</summary>
    public const int RezervariFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Ft.Protocol.Rezervare> _repeated_rezervari_codec
        = pb::FieldCodec.ForMessage(58, global::Ft.Protocol.Rezervare.Parser);
    private readonly pbc::RepeatedField<global::Ft.Protocol.Rezervare> rezervari_ = new pbc::RepeatedField<global::Ft.Protocol.Rezervare>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Ft.Protocol.Rezervare> Rezervari {
      get { return rezervari_; }
    }

    /// <summary>Field number for the "rezervareDTO" field.</summary>
    public const int RezervareDTOFieldNumber = 8;
    private global::Ft.Protocol.RezervareDTO rezervareDTO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ft.Protocol.RezervareDTO RezervareDTO {
      get { return rezervareDTO_; }
      set {
        rezervareDTO_ = value;
      }
    }

    /// <summary>Field number for the "rezervariDTO" field.</summary>
    public const int RezervariDTOFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Ft.Protocol.RezervareDTO> _repeated_rezervariDTO_codec
        = pb::FieldCodec.ForMessage(74, global::Ft.Protocol.RezervareDTO.Parser);
    private readonly pbc::RepeatedField<global::Ft.Protocol.RezervareDTO> rezervariDTO_ = new pbc::RepeatedField<global::Ft.Protocol.RezervareDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Ft.Protocol.RezervareDTO> RezervariDTO {
      get { return rezervariDTO_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Oficiu, other.Oficiu)) return false;
      if(!curse_.Equals(other.curse_)) return false;
      if (!object.Equals(Cursa, other.Cursa)) return false;
      if (!object.Equals(Rezervare, other.Rezervare)) return false;
      if(!rezervari_.Equals(other.rezervari_)) return false;
      if (!object.Equals(RezervareDTO, other.RezervareDTO)) return false;
      if(!rezervariDTO_.Equals(other.rezervariDTO_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (oficiu_ != null) hash ^= Oficiu.GetHashCode();
      hash ^= curse_.GetHashCode();
      if (cursa_ != null) hash ^= Cursa.GetHashCode();
      if (rezervare_ != null) hash ^= Rezervare.GetHashCode();
      hash ^= rezervari_.GetHashCode();
      if (rezervareDTO_ != null) hash ^= RezervareDTO.GetHashCode();
      hash ^= rezervariDTO_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (oficiu_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Oficiu);
      }
      curse_.WriteTo(output, _repeated_curse_codec);
      if (cursa_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Cursa);
      }
      if (rezervare_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Rezervare);
      }
      rezervari_.WriteTo(output, _repeated_rezervari_codec);
      if (rezervareDTO_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(RezervareDTO);
      }
      rezervariDTO_.WriteTo(output, _repeated_rezervariDTO_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (oficiu_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Oficiu);
      }
      size += curse_.CalculateSize(_repeated_curse_codec);
      if (cursa_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cursa);
      }
      if (rezervare_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rezervare);
      }
      size += rezervari_.CalculateSize(_repeated_rezervari_codec);
      if (rezervareDTO_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RezervareDTO);
      }
      size += rezervariDTO_.CalculateSize(_repeated_rezervariDTO_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.oficiu_ != null) {
        if (oficiu_ == null) {
          oficiu_ = new global::Ft.Protocol.Oficiu();
        }
        Oficiu.MergeFrom(other.Oficiu);
      }
      curse_.Add(other.curse_);
      if (other.cursa_ != null) {
        if (cursa_ == null) {
          cursa_ = new global::Ft.Protocol.Cursa();
        }
        Cursa.MergeFrom(other.Cursa);
      }
      if (other.rezervare_ != null) {
        if (rezervare_ == null) {
          rezervare_ = new global::Ft.Protocol.Rezervare();
        }
        Rezervare.MergeFrom(other.Rezervare);
      }
      rezervari_.Add(other.rezervari_);
      if (other.rezervareDTO_ != null) {
        if (rezervareDTO_ == null) {
          rezervareDTO_ = new global::Ft.Protocol.RezervareDTO();
        }
        RezervareDTO.MergeFrom(other.RezervareDTO);
      }
      rezervariDTO_.Add(other.rezervariDTO_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::Ft.Protocol.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (oficiu_ == null) {
              oficiu_ = new global::Ft.Protocol.Oficiu();
            }
            input.ReadMessage(oficiu_);
            break;
          }
          case 34: {
            curse_.AddEntriesFrom(input, _repeated_curse_codec);
            break;
          }
          case 42: {
            if (cursa_ == null) {
              cursa_ = new global::Ft.Protocol.Cursa();
            }
            input.ReadMessage(cursa_);
            break;
          }
          case 50: {
            if (rezervare_ == null) {
              rezervare_ = new global::Ft.Protocol.Rezervare();
            }
            input.ReadMessage(rezervare_);
            break;
          }
          case 58: {
            rezervari_.AddEntriesFrom(input, _repeated_rezervari_codec);
            break;
          }
          case 66: {
            if (rezervareDTO_ == null) {
              rezervareDTO_ = new global::Ft.Protocol.RezervareDTO();
            }
            input.ReadMessage(rezervareDTO_);
            break;
          }
          case 74: {
            rezervariDTO_.AddEntriesFrom(input, _repeated_rezervariDTO_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("GET_FILTERED_CURSE")] GetFilteredCurse = 3,
        [pbr::OriginalName("SAVE_REZERVARE")] SaveRezervare = 4,
        [pbr::OriginalName("SAVED_REZERVARE")] SavedRezervare = 5,
        [pbr::OriginalName("GET_ALL_CURSE")] GetAllCurse = 6,
        [pbr::OriginalName("GET_REZERVARE_DTO")] GetRezervareDto = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
